import { timestamp, files, shell } from '@sapper/service-worker';
import { precacheAndRoute } from 'workbox-precaching';
import { CacheFirst } from 'workbox-strategies';
import { registerRoute } from 'workbox-routing';
import { ExpirationPlugin } from 'workbox-expiration';

const ASSETS = `cache${timestamp}`;

// `shell` is an array of all the files generated by the bundler,
// `files` is an array of everything in the `static` directory
const to_cache = shell.concat(files);
const staticAssets = new Set(to_cache);

precacheAndRoute(shell);
precacheAndRoute(files);

registerRoute(
/* eslint-disable-next-line */
  new RegExp('https:\/\/producteursagri\.opendatasoft\.com'),
  new CacheFirst({
    cacheName: `ods-requests-${timestamp}`,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 3600 * 24,
      }),
    ],
  }),
);
